"""add level to popular phrases

Revision ID: 08ef631ace73
Revises: cf17a3a88250
Create Date: 2026-08-24 10:35:12.352801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ef631ace73'
down_revision: Union[str, Sequence[str], None] = 'cf17a3a88250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popular_phrases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popular_phrases', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
