"""add rejected_words table

Revision ID: 1f0fb915fa8c
Revises: 8a74865be012
Create Date: 2026-08-22 18:17:59.903604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0fb915fa8c'
down_revision: Union[str, Sequence[str], None] = '8a74865be012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('normalized_word', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_code', 'normalized_word', name='uq_rejected_word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected_words')
    # ### end Alembic commands ###
