"""add popular_phrases table for AI-generated phrase generation

Revision ID: 41c7a4563507
Revises: ee136f0d6102
Create Date: 2026-08-22 07:53:52.018026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c7a4563507'
down_revision: Union[str, Sequence[str], None] = 'ee136f0d6102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('phrase', sa.String(length=500), nullable=False),
    sa.Column('normalized_phrase', sa.String(length=500), nullable=False),
    sa.Column('pronunciation', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'normalized_phrase', name='uq_popular_phrase')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('popular_phrases')
    # ### end Alembic commands ###
