"""add learning sessions, notification log, streak fields, review indexes

Revision ID: 42e3b211edae
Revises: 4e9cade8b27d
Create Date: 2026-08-19 17:44:21.981060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e3b211edae'
down_revision: Union[str, Sequence[str], None] = '4e9cade8b27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('completed_words', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_learning_sessions_user_lang_status', ['user_id', 'language_code', 'status'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=16), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_type', 'scheduled_date', name='uq_notification_once_per_day')
    )
    op.create_table('learning_session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_word_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_new_word', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_word_id'], ['user_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_session_item_position'),
    sa.UniqueConstraint('session_id', 'user_word_id', name='uq_session_item_word')
    )
    with op.batch_alter_table('learning_session_items', schema=None) as batch_op:
        batch_op.create_index('ix_session_items_session_completed', ['session_id', 'completed'], unique=False)

    with op.batch_alter_table('user_words', schema=None) as batch_op:
        batch_op.create_index('ix_user_words_language_code', ['language_code'], unique=False)
        batch_op.create_index('ix_user_words_status', ['status'], unique=False)
        batch_op.create_index('ix_user_words_user_next_review', ['user_id', 'next_review_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_learning_date', sa.Date(), nullable=True))
        # NOT NULL columns added to an existing table need a default for
        # any rows already there - autogenerate omits it, so it's added
        # by hand here (matches the pattern in migration cc37901c0d0f).
        batch_op.add_column(
            sa.Column('current_streak', sa.Integer(), server_default=sa.text('0'), nullable=False)
        )
        batch_op.add_column(
            sa.Column('longest_streak', sa.Integer(), server_default=sa.text('0'), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('longest_streak')
        batch_op.drop_column('current_streak')
        batch_op.drop_column('last_learning_date')

    with op.batch_alter_table('user_words', schema=None) as batch_op:
        batch_op.drop_index('ix_user_words_user_next_review')
        batch_op.drop_index('ix_user_words_status')
        batch_op.drop_index('ix_user_words_language_code')

    with op.batch_alter_table('learning_session_items', schema=None) as batch_op:
        batch_op.drop_index('ix_session_items_session_completed')

    op.drop_table('learning_session_items')
    op.drop_table('notification_logs')
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_learning_sessions_user_lang_status')

    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
