"""add word, word_translation, word_example, word_form, user_word tables

Revision ID: 4e9cade8b27d
Revises: cc37901c0d0f
Create Date: 2026-08-19 17:14:43.816464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9cade8b27d'
down_revision: Union[str, Sequence[str], None] = 'cc37901c0d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('normalized_word', sa.String(length=255), nullable=False),
    sa.Column('part_of_speech', sa.String(length=32), nullable=True),
    sa.Column('pronunciation', sa.String(length=255), nullable=True),
    sa.Column('phonetic', sa.String(length=255), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('is_verb', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'normalized_word', name='uq_words_language_normalized')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_normalized_word'), ['normalized_word'], unique=False)

    op.create_table('user_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetition_stage', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('difficulty_score', sa.Float(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_table('word_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('example_text', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_examples_word_id'), ['word_id'], unique=False)

    op.create_table('word_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=64), nullable=False),
    sa.Column('form', sa.String(length=255), nullable=False),
    sa.Column('grammatical_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_forms_word_id'), ['word_id'], unique=False)

    op.create_table('word_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('usage_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_translations_word_id'), ['word_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_translations_word_id'))

    op.drop_table('word_translations')
    with op.batch_alter_table('word_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_forms_word_id'))

    op.drop_table('word_forms')
    with op.batch_alter_table('word_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_examples_word_id'))

    op.drop_table('word_examples')
    op.drop_table('user_words')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_normalized_word'))

    op.drop_table('words')
    # ### end Alembic commands ###
