"""add user_phrases table for useful phrases feature

Revision ID: 5be8c9e75efd
Revises: fb344dc67df5
Create Date: 2026-08-22 06:36:49.608002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be8c9e75efd'
down_revision: Union[str, Sequence[str], None] = 'fb344dc67df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('phrase', sa.String(length=500), nullable=False),
    sa.Column('normalized_phrase', sa.String(length=500), nullable=False),
    sa.Column('translation', sa.String(length=500), nullable=False),
    sa.Column('pronunciation', sa.String(length=500), nullable=True),
    sa.Column('register', sa.String(length=32), nullable=True),
    sa.Column('situation', sa.String(length=64), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_code', 'normalized_phrase', name='uq_user_phrase')
    )
    with op.batch_alter_table('user_phrases', schema=None) as batch_op:
        batch_op.create_index('ix_user_phrases_user_language', ['user_id', 'language_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_phrases', schema=None) as batch_op:
        batch_op.drop_index('ix_user_phrases_user_language')

    op.drop_table('user_phrases')
    # ### end Alembic commands ###
