"""add trigger to word generation log

Revision ID: a2ca25ab3e06
Revises: d7e472cbbb22
Create Date: 2026-08-20 14:53:12.652254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ca25ab3e06'
down_revision: Union[str, Sequence[str], None] = 'd7e472cbbb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_generation_logs', schema=None) as batch_op:
        # NOT NULL column added to an existing table needs a default for
        # any rows already there - autogenerate omits it (matches the
        # pattern in migration d7e472cbbb22 for user_words.source).
        batch_op.add_column(
            sa.Column('trigger', sa.String(length=16), server_default='daily_quota', nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_generation_logs', schema=None) as batch_op:
        batch_op.drop_column('trigger')

    # ### end Alembic commands ###
