"""add review logs table

Revision ID: a8a1e325322e
Revises: 33ef1fcbc844
Create Date: 2026-08-26 09:47:30.318180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a1e325322e'
down_revision: Union[str, Sequence[str], None] = '33ef1fcbc844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_word_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('correct_delta', sa.Integer(), nullable=False),
    sa.Column('wrong_delta', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_word_id'], ['user_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.create_index('ix_review_logs_user_reviewed_at', ['user_id', 'reviewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_review_logs_user_reviewed_at')

    op.drop_table('review_logs')
    # ### end Alembic commands ###
