"""add user_word source field and word generation log

Revision ID: d7e472cbbb22
Revises: 42e3b211edae
Create Date: 2026-08-20 09:27:25.033915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e472cbbb22'
down_revision: Union[str, Sequence[str], None] = '42e3b211edae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('generated_amount', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_words', schema=None) as batch_op:
        # NOT NULL column added to an existing table needs a default for
        # any rows already there - autogenerate omits it (matches the
        # pattern in migration 42e3b211edae for current_streak).
        batch_op.add_column(
            sa.Column('source', sa.String(length=16), server_default='dictionary', nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_words', schema=None) as batch_op:
        batch_op.drop_column('source')

    op.drop_table('word_generation_logs')
    # ### end Alembic commands ###
