"""add popular_phrase_translations cache table

Revision ID: ee136f0d6102
Revises: 5be8c9e75efd
Create Date: 2026-08-22 07:38:48.105274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee136f0d6102'
down_revision: Union[str, Sequence[str], None] = '5be8c9e75efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_phrase_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('translation_language', sa.String(length=8), nullable=False),
    sa.Column('phrase_index', sa.Integer(), nullable=False),
    sa.Column('translation', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['translation_language'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'translation_language', 'phrase_index', name='uq_popular_phrase_translation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('popular_phrase_translations')
    # ### end Alembic commands ###
