"""add learning goal work industry and selected topics to user languages

Revision ID: f19bc5261835
Revises: a2ca25ab3e06
Create Date: 2026-08-21 10:49:27.073430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19bc5261835'
down_revision: Union[str, Sequence[str], None] = 'a2ca25ab3e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_goal', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('work_industry', sa.String(length=64), nullable=True))
        # NOT NULL column added to an existing table needs a default for
        # any rows already there - autogenerate omits it (same pattern as
        # migration a2ca25ab3e06 for word_generation_logs.trigger). Every
        # existing user_language ends up with selected_topics = [], never
        # destroying anything, matching the spec's explicit "must not
        # force a destructive migration" requirement.
        batch_op.add_column(sa.Column('selected_topics', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_languages', schema=None) as batch_op:
        batch_op.drop_column('selected_topics')
        batch_op.drop_column('work_industry')
        batch_op.drop_column('learning_goal')

    # ### end Alembic commands ###
