"""add repetition-system stage fields: review mode, notification word count, per-slot toggles, verb conjugation cache, notification word history

Revision ID: fb344dc67df5
Revises: f19bc5261835
Create Date: 2026-08-21 14:42:16.010337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb344dc67df5'
down_revision: Union[str, Sequence[str], None] = 'f19bc5261835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_ids', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        # NOT NULL columns added to an existing table need a default for
        # any rows already there - autogenerate omits it (same gap as
        # migrations a2ca25ab3e06 and f19bc5261835 before this one).
        # Every existing user ends up with all three slots still enabled
        # and the same 4-word default the spec calls for - nothing about
        # their current notification behavior changes.
        batch_op.add_column(sa.Column('morning_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.add_column(sa.Column('afternoon_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.add_column(sa.Column('evening_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.add_column(sa.Column('notification_word_count', sa.Integer(), server_default='4', nullable=False))
        batch_op.add_column(sa.Column('review_mode', sa.String(length=16), nullable=True))

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verb_conjugation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('verb_conjugation')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('review_mode')
        batch_op.drop_column('notification_word_count')
        batch_op.drop_column('evening_enabled')
        batch_op.drop_column('afternoon_enabled')
        batch_op.drop_column('morning_enabled')

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_column('word_ids')

    # ### end Alembic commands ###
